package(default_visibility = ["//visibility:public"])

cc_test(
    name = "sorting_test",
    srcs = ["sorting_test.cc"],
    deps = [
        "//src/algorithms:algorithms",
        "@com_google_googletest//:gtest_main",
    ],
)
