package(default_visibility = ["//visibility:public"])

cc_library(
    name = "utils_examples",
    srcs = [
        "string_utils_example.cc",
        "file_utils_example.cc",
    ],
    hdrs = [],
    deps = [
        "//src/utils:utils",
    ],
)