package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math_examples",
    srcs = [
        "statistics_example.cc",
    ],
    hdrs = [],
    deps = [
        "//src/math:math",
    ],
)