package(default_visibility = ["//visibility:public"])

cc_library(
    name = "data_structures",
    hdrs = [
        "thread_safe_queue.h",
        "lru_cache.h",
    ],
)

cc_library(
    name = "thread_safe_queue",
    hdrs = ["thread_safe_queue.h"],
)

cc_library(
    name = "lru_cache",
    hdrs = ["lru_cache.h"],
)
