package(default_visibility = ["//visibility:public"])

cc_test(
    name = "statistics_test",
    srcs = ["statistics_test.cc"],
    deps = [
        "//src/math:math",
        "@com_google_googletest//:gtest_main",
    ],
)
