package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//examples/utils:utils_examples",
        "//examples/algorithms:algorithms_examples",
        "//examples/data_structures:data_structures_examples",
        "//examples/math:math_examples",
    ],
)
