package(default_visibility = ["//visibility:public"])

cc_library(
    name = "data_structures_examples",
    srcs = [
        "lru_cache_example.cc",
        "thread_safe_queue_example.cc",
        "custom_object_example.cc",
    ],
    hdrs = [],
    deps = [
        "//src/data_structures:data_structures",
    ],
)