package(default_visibility = ["//visibility:public"])

cc_library(
    name = "algorithms_examples",
    srcs = [
        "sorting_example.cc",
    ],
    hdrs = [],
    deps = [
        "//src/algorithms:algorithms",
    ],
)