package(default_visibility = ["//visibility:public"])

cc_test(
    name = "string_utils_test",
    srcs = ["string_utils_test.cc"],
    deps = [
        "//src/utils:string_utils",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "file_utils_test",
    srcs = ["file_utils_test.cc"],
    deps = [
        "//src/utils:file_utils",
        "@com_google_googletest//:gtest_main",
    ],
)
